"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _candidate_dashboard from './candidate-dashboard.bones.json'

registerBones({
  "candidate-dashboard": _candidate_dashboard,
})
