"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _login_form from './login-form.bones.json'

registerBones({
  "login-form": _login_form,
})
